export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white py-12">
      <div className="max-w-4xl mx-auto px-4">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms & Conditions</h1>

        <div className="prose prose-lg max-w-none">
          <p className="text-sm text-gray-600 mb-6">Last Updated: January 2025</p>

          <p>These Terms & Conditions ("Terms") govern your use of the Dopair platform, including both the free Digital Dopamine Addiction Scale (DDAS) assessment and Dopair Premium subscription services, operated by Middlez Pty Ltd ("we," "us," or "our").</p>

          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using our services, creating an account, or subscribing to Dopair Premium, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use our services.</p>

          <h2>2. Service Description</h2>

          <h3>2.1 Free Services</h3>
          <ul>
            <li>Digital Dopamine Addiction Scale (DDAS) assessment</li>
            <li>Basic educational content and resources</li>
            <li>Limited access to platform features</li>
          </ul>

          <h3>2.2 Dopair Premium Subscription</h3>
          <p>Our premium subscription service includes:</p>
          <ul>
            <li>Unlimited access to AI-powered recovery coach</li>
            <li>Personalized recovery programs and pathways</li>
            <li>Progress tracking and advanced analytics</li>
            <li>Premium content library and resources</li>
            <li>Priority customer support</li>
            <li>Enhanced assessment features</li>
          </ul>

          <h2>3. Subscription Terms & Billing</h2>

          <h3>3.1 Subscription Plans</h3>
          <ul>
            <li><strong>Dopair Premium Monthly</strong>: $29.00 USD per month</li>
            <li>Additional plans may be offered from time to time</li>
          </ul>

          <h3>3.2 Billing Cycle</h3>
          <ul>
            <li>Monthly subscriptions are billed every 30 days from your subscription start date</li>
            <li>Payment is charged in advance for each billing period</li>
            <li>All fees are non-refundable except as expressly stated in these Terms</li>
          </ul>

          <h3>3.3 Payment Processing</h3>
          <ul>
            <li>Payments are processed by Stripe, Inc., subject to their terms of service</li>
            <li>Failed payments may result in service suspension or termination</li>
            <li>We may retry failed payments for up to 30 days</li>
          </ul>

          <h3>3.4 Grace Period for Payment Failures</h3>
          <ul>
            <li>If your payment fails, you will receive a 7-day grace period with limited access</li>
            <li>During the grace period, you retain access to the AI coach with reduced daily limits (20 messages instead of 100)</li>
            <li>Premium content access is suspended during the grace period</li>
            <li>If payment is not resolved within 7 days, your account will be downgraded to free tier</li>
          </ul>

          <h2>4. Cancellation & Refunds</h2>

          <h3>4.1 Cancellation</h3>
          <ul>
            <li>You may cancel your subscription at any time through your account settings or by contacting support</li>
            <li>Cancellation takes effect at the end of your current billing period</li>
            <li>You will retain premium access until the end of your paid period</li>
            <li>No partial refunds are provided for unused portions of your subscription</li>
          </ul>

          <h3>4.2 Subscription Pausing</h3>
          <ul>
            <li>Premium subscribers may pause their subscription for up to 1 month per year</li>
            <li>During a pause, billing is suspended and premium features are temporarily disabled</li>
            <li>Paused subscriptions automatically resume after the pause period</li>
          </ul>

          <h2>5. AI Coach and Digital Content</h2>

          <h3>5.1 AI-Powered Services</h3>
          <ul>
            <li>Our AI coach provides personalized guidance based on evidence-based recovery methods</li>
            <li>AI responses are generated by artificial intelligence and should not replace professional medical advice</li>
            <li>We do not guarantee the accuracy or effectiveness of AI-generated content</li>
          </ul>

          <h3>5.2 Professional Medical Advice Disclaimer</h3>
          <ul>
            <li>Our services are not intended to diagnose, treat, cure, or prevent any medical condition</li>
            <li>The AI coach and assessments are educational tools and should not replace professional healthcare</li>
            <li>If you are experiencing a mental health crisis, please contact emergency services or a qualified healthcare provider immediately</li>
          </ul>

          <h2>6. Limitation of Liability</h2>
          <ul>
            <li>Our services are provided "as is" without warranties of any kind</li>
            <li>We are not liable for any indirect, incidental, or consequential damages</li>
            <li>Our total liability is limited to the amount you paid for services in the 12 months preceding any claim</li>
          </ul>

          <h2>7. Contact Information</h2>
          <p>For questions about these Terms, billing issues, or general support:</p>
          <p>
            <strong>Middlez Pty Ltd</strong><br />
            Email: support@dopair.app<br />
            Website: https://premium.dopair.app
          </p>

          <div className="mt-12 pt-8 border-t border-gray-200">
            <p className="text-sm text-gray-600">
              <a href="/privacy" className="text-indigo-600 hover:underline">Privacy Policy</a> |{' '}
              <a href="/account" className="text-indigo-600 hover:underline">Account Settings</a> |{' '}
              <a href="/dashboard" className="text-indigo-600 hover:underline">Dashboard</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}